---
# -------------------------------------------------------------------------------------------------------------------- #
- name: include variables
  include_vars: "{{ item }}"
  with_fileglob:
    - "vars/*.yaml"

# -------------------------------------------------------------------------------------------------------------------- #
