---
# setup docker-compose project --------------------------------------------------------------------------------------- #
docker_compose_project: "{{ project_name }}"
docker_compose_config:
  version: 3.7

  secrets:
    ca.pem:
      file: "{{ ca }}"
    cert.pem:
      file: "{{ cert }}"
    key.pem:
      file: "{{ key }}"

  services:
    - name: cockroach
      options:
        image: cockroachdb/cockroach:v20.1.3
        command: start --http-port 26256 --insecure
        volumes:
          - "{{ data_dir }}/{{ project_name }}/cockroach:/cockroach/cockroach-data"
        ports:
          - 127.0.0.1:26257:26257 # Cockroach
          - 127.0.0.1:26256:26256 # WebUI

    - name: redis
      options:
        image: redis:5-alpine
        command: redis-server --appendonly yes
        volumes:
          - "{{ data_dir }}/{{ project_name }}/redis:/data"
        ports:
          - 127.0.0.1:6379:6379

    - name: stack
      options:
        image: thethingsnetwork/lorawan-stack:3.8.4
        entrypoint: ttn-lw-stack -c /config/ttn-lw-stack.yml
        command: start
        depends_on:
          - cockroach
          - redis
        volumes:
          - "{{ data_dir }}/{{ project_name }}/stack/blob:/srv/ttn-lorawan/public/blob"
          - "{{ data_dir }}/{{ project_name }}/stack/config:/config:ro"
        environment:
          TTN_LW_BLOB_LOCAL_DIRECTORY: /srv/ttn-lorawan/public/blob
          TTN_LW_IS_DATABASE_URI: postgres://root@cockroach:26257/ttn_lorawan?sslmode=disable
          TTN_LW_REDIS_ADDRESS: redis:6379
          TTN_LW_TLS_SOURCE: file
          TTN_LW_TLS_ROOT_CA: /run/secrets/ca.pem
          TTN_LW_TLS_CERTIFICATE: /run/secrets/cert.pem
          TTN_LW_TLS_KEY: /run/secrets/key.pem
        ports:
          - 1881:1881
          - 8881:8881
          - 1882:1882
          - 8882:8882
          - 1883:1883
          - 8883:8883
          - 1884:1884
          - 8884:8884
          - 1885:1885
          - 8885:8885
          - 1887:1887
          - 8887:8887
          - 1700:1700/udp
        secrets:
          - ca.pem
          - cert.pem
          - key.pem

# -------------------------------------------------------------------------------------------------------------------- #
